import type { Locale } from "./types";
const ko = {
  automatic: "자동",
  directionReview: "입금인지 지출인지 확인 후 선택하세요.", reviewedDuplicate: "같은 내역이 이미 있어 다시 등록하지 않습니다.",
  encoding: "텍스트 인코딩(글자가 깨질 때)", headerRow: "제목 행", noHeader: "제목 행 없음", debitColumn: "출금 금액 열(분리된 경우)", typeColumn: "거래 종류 열", idColumn: "거래 번호 열", nextPage: "다음 내역", previousPage: "이전 내역", incomplete: "확인이 필요한 내역은 수정 후 선택해주세요.",
  title: "소비내역 가져오기", choose: "파일 선택", supported: "PDF, 엑셀(XLSX·XLS·ODS), CSV·TSV, OFX·QIF, JSON, 텍스트·HTML·DOCX·ODT와 이미지(PNG·JPG·WEBP 등)를 읽습니다. 파일 이름보다 실제 내용을 확인합니다.",
  help: "인식한 날짜·금액·사용처를 확인하고 수정한 다음 등록하세요. 잔액·입금·실패한 결제는 제외하며, 중복과 취소·환불은 따로 표시합니다.",
  reading: "파일을 읽는 중", failed: "파일을 읽지 못했습니다. 형식과 암호를 확인해주세요.", unsupported: "이 파일의 내용을 읽을 수 없습니다. PDF, 엑셀, CSV 또는 이미지로 내보낸 파일을 선택해주세요.",
  password: "파일 암호(필요한 경우)", language: "이미지·스캔 문자 언어", latin: "영어·프랑스어 등 라틴 문자", korean: "한국어", chinese: "중국어", japanese: "일본어", hindi: "힌디어",
  ocrAndroid: "이미지·스캔 PDF 인식은 Android 앱에서 사용할 수 있습니다.", size: "파일이 너무 큽니다. 40 MB 이하 파일로 나눠주세요.", limit: "인식 범위를 넘었습니다. 더 작은 파일로 나눠주세요.", encrypted: "암호가 필요하거나 지원하지 않는 암호화 방식입니다. 암호를 확인하고, 계속 실패하면 잠금 해제한 PDF·엑셀 또는 CSV로 내보내주세요.",
  table: "시트·표 선택", columns: "표의 열 확인", none: "선택 안 함", dateOrder: "날짜 순서", auto: "자동(모호한 날짜는 확인)", dmy: "일/월/연도", mdy: "월/일/연도",
  sign: "금액 표시 방식", negative: "음수가 지출", positive: "양수가 지출", expensesOnly: "모두 지출인 파일", dateColumn: "날짜 열", merchantColumn: "사용처 열", amountColumn: "결제 금액 열", currencyColumn: "화폐 열", statusColumn: "거래 상태 열", creditColumn: "입금 열(분리된 경우)",
  defaultCurrency: "화폐가 없는 내역의 화폐", target: "등록할 가계부", newGeneral: "화폐별 새 일반 가계부", newTitle: "새 가계부 이름", fileName: "파일", rows: "검토할 내역", ignored: "제외된 행", duplicate: "이미 있는 내역", invalid: "날짜·금액·사용처 확인 필요", cancelled: "취소·환불 확인 필요", excluded: "잔액·입금·취소·실패 등", refundMatched: "같은 파일의 환불을 반영함", unknown: "인식하지 못한 행", selected: "선택한 내역", total: "등록할 금액", confirm: "확인하고 등록", saved: "소비내역을 등록했습니다.", saveFailed: "저장하지 못했습니다. 가계부와 선택한 내역을 확인해주세요.", empty: "자동으로 찾은 소비내역이 없습니다. 표의 열을 지정하거나 원문을 보고 행을 추가할 수 있습니다.",
  addRow: "직접 행 추가", original: "원문 확인", selectAll: "유효한 내역 선택", selectNone: "전체 선택 해제", payerHelp: "선택한 여행 내역의 결제자와 함께 나눌 사람을 지정하세요.", wrongCurrency: "가계부와 화폐가 다릅니다. 같은 화폐의 가계부나 새 가계부를 선택해주세요.",
  sharePdf: "동행에게 PDF 보내기", shareHelp: "카카오톡·WhatsApp 등으로 PDF를 보내세요. 이 앱에서 만든 PDF는 결제자와 분담 내역까지 다시 가져와 기존 여행에 합칠 수 있습니다.", shared: "PDF 공유창을 열었습니다.", downloaded: "PDF 파일을 다운로드했습니다.", saving: "PDF 만드는 중", saveHelp: "전체 기간의 내역을 PDF로 저장합니다. 휴대폰 저장 위치를 선택하세요.", parsedLedger: "가계부 PDF의 원본 내역을 찾았습니다.",
  newRow: "새 내역", fileChanged: "가계부가 변경되었습니다. 내역을 다시 확인해주세요.", sheetEmpty: "읽을 수 있는 행이 없습니다.", summary: "기간·건수·화폐별 금액", of: "/", keep: "등록", cancelledHelp: "취소·환불 행은 지출로 등록하지 않습니다. 저장된 지출과 일치하면 아래에서 확인 후 금액을 조정합니다.", adjustments: "저장된 지출 조정", adjustmentHelp: "다른 파일에서 확인된 환불·취소입니다. 맞는 내역만 선택하면 기존 지출의 금액을 줄이거나 삭제합니다.", refund: "환불", scanNotice: "문자 인식 결과입니다. 날짜·소수점·금액을 원본과 확인해주세요.",
};
type Key = keyof typeof ko;
const en: Record<Key, string> = {
  automatic: "Automatic",
  directionReview: "Check whether this is an expense or incoming money before selecting.", reviewedDuplicate: "This item already exists and will not be imported again.",
  encoding: "Text encoding (for unreadable characters)", headerRow: "Header row", noHeader: "No header row", debitColumn: "Outgoing amount column (if separate)", typeColumn: "Transaction type column", idColumn: "Transaction ID column", nextPage: "Next items", previousPage: "Previous items", incomplete: "Edit items needing review, then select them.",
  title: "Import expenses", choose: "Choose file", supported: "Reads PDF, Excel (XLSX, XLS, ODS), CSV/TSV, OFX/QIF, JSON, text, HTML, DOCX/ODT and images (PNG, JPG, WEBP and more). Checks the contents as well as the file name.",
  help: "Check and edit dates, amounts and merchants before importing. Balances, incoming money and failed payments are excluded; duplicates and refunds are shown separately.",
  reading: "Reading file", failed: "Could not read this file. Check its format and password.", unsupported: "This file cannot be read. Choose a PDF, spreadsheet, CSV or image export.", password: "File password (if needed)", language: "Image and scan text language", latin: "Latin script (English, French and more)", korean: "Korean", chinese: "Chinese", japanese: "Japanese", hindi: "Hindi",
  ocrAndroid: "Image and scanned PDF recognition is available in the Android app.", size: "Split this file into files no larger than 40 MB.", limit: "The reading limit was reached. Split the file into smaller parts.", encrypted: "A password is needed or this encryption is unsupported. Check the password; if it still fails, export an unlocked PDF, spreadsheet or CSV.",
  table: "Choose sheet or table", columns: "Check table columns", none: "Not selected", dateOrder: "Date order", auto: "Automatic (check ambiguous dates)", dmy: "Day/month/year", mdy: "Month/day/year",
  sign: "Amount convention", negative: "Negative amounts are expenses", positive: "Positive amounts are expenses", expensesOnly: "File contains expenses only", dateColumn: "Date column", merchantColumn: "Merchant column", amountColumn: "Payment amount column", currencyColumn: "Currency column", statusColumn: "Transaction status column", creditColumn: "Incoming amount column (if separate)",
  defaultCurrency: "Currency for items without one", target: "Destination ledger", newGeneral: "New everyday ledger per currency", newTitle: "New ledger name", fileName: "File", rows: "Items to review", ignored: "Excluded rows", duplicate: "Already recorded", invalid: "Check date, amount and merchant", cancelled: "Cancellation or refund to review", excluded: "Balance, income, cancellation or failed payment", refundMatched: "Refund from the same file applied", unknown: "Unrecognized row", selected: "Selected items", total: "Amount to import", confirm: "Confirm and import", saved: "Expenses imported.", saveFailed: "Could not save. Check the ledger and selected items.", empty: "No expenses were found automatically. Assign table columns or add rows using the original text.",
  addRow: "Add row manually", original: "View original", selectAll: "Select valid items", selectNone: "Clear selection", payerHelp: "Choose the payer and people sharing these travel expenses.", wrongCurrency: "This currency differs from the ledger. Choose a matching ledger or a new ledger.",
  sharePdf: "Send PDF to companions", shareHelp: "Send a PDF through WhatsApp, KakaoTalk or another app. PDFs created by this app can be imported into an existing trip with their payer and split details.", shared: "PDF sharing opened.", downloaded: "PDF downloaded.", saving: "Creating PDF", saveHelp: "Saves expenses from all dates as a PDF. Choose a location on your phone.", parsedLedger: "Original ledger data found in the PDF.",
  newRow: "New item", fileChanged: "The ledger changed. Check the items again.", sheetEmpty: "No readable rows.", summary: "Date range, count and totals by currency", of: "/", keep: "Import", cancelledHelp: "Cancellations and refunds are not imported as expenses. If a saved expense matches, review it below before changing the amount.", adjustments: "Saved expense adjustments", adjustmentHelp: "Refunds and cancellations found in another file. Select only matches you approve; the saved expense will be reduced or removed.", refund: "Refund", scanNotice: "Text was recognized from an image. Compare dates, decimal points and amounts with the original.",
};
const fr: Record<Key, string> = {
  automatic: "Automatique",
  directionReview: "Vérifiez s’il s’agit d’une dépense ou d’une entrée d’argent avant de sélectionner.", reviewedDuplicate: "Cette opération existe déjà et ne sera pas importée à nouveau.",
  encoding: "Encodage du texte (si les caractères sont illisibles)", headerRow: "Ligne d’en-tête", noHeader: "Sans en-tête", debitColumn: "Colonne des débits (si séparée)", typeColumn: "Colonne du type d’opération", idColumn: "Colonne de l’identifiant", nextPage: "Opérations suivantes", previousPage: "Opérations précédentes", incomplete: "Corrigez les opérations à vérifier, puis sélectionnez-les.",
  title: "Importer des dépenses", choose: "Choisir un fichier", supported: "Lit les PDF, fichiers Excel (XLSX, XLS, ODS), CSV/TSV, OFX/QIF, JSON, textes, HTML, DOCX/ODT et images (PNG, JPG, WEBP, etc.). Vérifie le contenu et le nom du fichier.",
  help: "Vérifiez et corrigez les dates, montants et commerçants avant l’importation. Les soldes, entrées d’argent et paiements échoués sont exclus. Les doublons et remboursements sont signalés.",
  reading: "Lecture du fichier", failed: "Lecture impossible. Vérifiez le format et le mot de passe.", unsupported: "Ce fichier ne peut pas être lu. Choisissez un export PDF, un tableau, un CSV ou une image.", password: "Mot de passe du fichier (si nécessaire)", language: "Langue du texte des images", latin: "Alphabet latin (français, anglais, etc.)", korean: "Coréen", chinese: "Chinois", japanese: "Japonais", hindi: "Hindi",
  ocrAndroid: "La reconnaissance des images et PDF numérisés est disponible dans l’application Android.", size: "Divisez le fichier en parties de 40 Mo maximum.", limit: "La limite de lecture est atteinte. Divisez le fichier en parties plus petites.", encrypted: "Un mot de passe est requis ou ce chiffrement n’est pas pris en charge. Vérifiez le mot de passe ; si l’échec persiste, exportez un PDF, tableau ou CSV déverrouillé.",
  table: "Choisir une feuille ou un tableau", columns: "Vérifier les colonnes", none: "Non sélectionnée", dateOrder: "Ordre des dates", auto: "Automatique (vérifier les dates ambiguës)", dmy: "Jour/mois/année", mdy: "Mois/jour/année",
  sign: "Convention des montants", negative: "Montants négatifs = dépenses", positive: "Montants positifs = dépenses", expensesOnly: "Fichier de dépenses uniquement", dateColumn: "Colonne des dates", merchantColumn: "Colonne des commerçants", amountColumn: "Colonne des paiements", currencyColumn: "Colonne des devises", statusColumn: "Colonne du statut", creditColumn: "Colonne des entrées d’argent (si séparée)",
  defaultCurrency: "Devise des opérations sans devise", target: "Carnet de destination", newGeneral: "Nouveau carnet quotidien par devise", newTitle: "Nom du nouveau carnet", fileName: "Fichier", rows: "Opérations à vérifier", ignored: "Lignes exclues", duplicate: "Déjà enregistrée", invalid: "Vérifier date, montant et commerçant", cancelled: "Annulation ou remboursement à vérifier", excluded: "Solde, entrée d’argent, annulation ou échec", refundMatched: "Remboursement du même fichier déduit", unknown: "Ligne non reconnue", selected: "Opérations sélectionnées", total: "Montant à importer", confirm: "Confirmer et importer", saved: "Dépenses importées.", saveFailed: "Enregistrement impossible. Vérifiez le carnet et les opérations.", empty: "Aucune dépense détectée automatiquement. Indiquez les colonnes ou ajoutez des lignes à partir du texte original.",
  addRow: "Ajouter une ligne", original: "Voir l’original", selectAll: "Sélectionner les opérations valides", selectNone: "Tout désélectionner", payerHelp: "Choisissez qui a payé et qui partage ces dépenses de voyage.", wrongCurrency: "La devise diffère de celle du carnet. Choisissez un carnet correspondant ou un nouveau carnet.",
  sharePdf: "Envoyer le PDF aux compagnons", shareHelp: "Envoyez le PDF via WhatsApp, KakaoTalk ou une autre application. Les PDF créés ici peuvent être fusionnés avec un voyage existant en conservant les payeurs et les répartitions.", shared: "Partage du PDF ouvert.", downloaded: "PDF téléchargé.", saving: "Création du PDF", saveHelp: "Enregistre toutes les dépenses dans un PDF. Choisissez un emplacement sur le téléphone.", parsedLedger: "Données originales du carnet trouvées dans le PDF.",
  newRow: "Nouvelle opération", fileChanged: "Le carnet a changé. Vérifiez à nouveau les opérations.", sheetEmpty: "Aucune ligne lisible.", summary: "Période, nombre et montants par devise", of: "/", keep: "Importer", cancelledHelp: "Les annulations et remboursements ne sont pas importés comme dépenses. Si une dépense enregistrée correspond, vérifiez-la ci-dessous avant de modifier son montant.", adjustments: "Ajustements des dépenses enregistrées", adjustmentHelp: "Remboursements et annulations trouvés dans un autre fichier. Sélectionnez uniquement les correspondances approuvées ; la dépense sera réduite ou supprimée.", refund: "Remboursement", scanNotice: "Texte reconnu sur une image. Vérifiez dates, décimales et montants avec l’original.",
};
export function documentText(locale: Locale, key: Key): string { return ({ ko, en, fr })[locale][key]; }
