import type { Locale } from "./types";

const ko = {
  move: "여행 가계부로 옮기기", moveTitle: "지출 옮기기", destination: "옮길 여행 가계부", moveHelp: "날짜·금액·화폐를 그대로 옮깁니다. 생활 가계부에서는 제거되고, 선택한 결제자와 참가자를 기준으로 여행 정산에 반영됩니다.", noTravel: "먼저 여행 가계부를 만들고 참가자를 추가해주세요.", noPeople: "이 여행 가계부에 참가자를 먼저 추가해주세요.", moved: "여행 가계부로 옮겼습니다.", moveFailed: "지출을 옮기지 못했습니다. 내역과 참가자를 다시 확인해주세요.",
  shareFile: "가계부 파일 보내기", shareSummary: "요약 공유", receive: "동행 내역 가져오기", shareHelp: "동행에게 가계부 파일을 보내세요. 받은 사람은 ‘동행 내역 가져오기’에서 파일을 선택해 기존 여행에 합칠 수 있습니다. 결제자와 나눌 금액이 그대로 전달됩니다.", fileSent: "가계부 파일을 공유했습니다.", importTitle: "여행 내역 합치기", incoming: "받은 가계부", target: "저장할 여행 가계부", newTab: "새 여행 가계부로 저장", mapping: "참가자 연결", mappingHelp: "왼쪽은 받은 파일의 참가자입니다. 같은 사람이라면 내 여행의 참가자를 선택하세요. 이름이 같아도 다른 사람이라면 새 참가자로 추가하세요.", newPerson: "새 참가자로 추가", preview: "합친 내역 확인", added: "추가 지출", duplicates: "이미 있는 지출", conflicts: "내용이 다른 지출", conflictHelp: "같은 기록의 내용이 달라 기존 내용을 유지합니다. 아래 내역을 확인한 뒤 필요하면 기존 지출을 편집하세요.", addedTotal: "추가되는 금액", resultTotal: "합친 총 지출", merge: "확인하고 합치기", importSaved: "여행 내역을 저장했습니다.", importFailed: "내역을 합치지 못했습니다. 참가자 연결과 가계부 용량을 확인해주세요.", invalidPreview: "참가자 연결을 모두 확인해주세요. 참가자·지출·화폐 개수 한도를 넘으면 합칠 수 없습니다.", recordCount: "지출 수", saveNew: "확인하고 새로 저장", resultSettlement: "합친 뒤 정산", changed: "가계부가 변경되었습니다. 미리보기를 다시 확인해주세요.",
};
type Key = keyof typeof ko;
const en: Record<Key, string> = {
  move: "Move to a travel ledger", moveTitle: "Move expense", destination: "Destination travel ledger", moveHelp: "The date, amount, and currency stay the same. The expense is removed from the daily ledger and included in the trip settlement using the payer and people you select.", noTravel: "Create a travel ledger and add participants first.", noPeople: "Add participants to this travel ledger first.", moved: "Expense moved to the travel ledger.", moveFailed: "Could not move this expense. Check the expense and participants.",
  shareFile: "Send ledger file", shareSummary: "Share summary", receive: "Import companion’s expenses", shareHelp: "Send the ledger file to your companions. They can choose it under ‘Import companion’s expenses’ and merge it into their trip. Payers and exact shares are preserved.", fileSent: "Ledger file shared.", importTitle: "Merge travel expenses", incoming: "Received ledger", target: "Save to travel ledger", newTab: "Save as a new travel ledger", mapping: "Match participants", mappingHelp: "The people on the left are from the received file. Select someone in your trip if they are the same person. Add a new participant if they are different, even when their names match.", newPerson: "Add as a new participant", preview: "Review merged expenses", added: "New expenses", duplicates: "Already included", conflicts: "Different versions", conflictHelp: "These records have different details, so your existing version is kept. Review them below and edit the existing expenses if needed.", addedTotal: "Amount to add", resultTotal: "Combined spending", merge: "Confirm and merge", importSaved: "Travel expenses saved.", importFailed: "Could not merge expenses. Check participant matches and ledger capacity.", invalidPreview: "Check every participant match. A merge cannot exceed the participant, expense, or currency limits.", recordCount: "Expenses", saveNew: "Confirm and save new ledger", resultSettlement: "Settlement after merge", changed: "The ledger changed. Review the updated preview before continuing.",
};
const fr: Record<Key, string> = {
  move: "Déplacer vers un carnet de voyage", moveTitle: "Déplacer la dépense", destination: "Carnet de voyage de destination", moveHelp: "La date, le montant et la devise sont conservés. La dépense est retirée du carnet quotidien et intégrée au règlement du voyage selon le payeur et les participants choisis.", noTravel: "Créez d’abord un carnet de voyage et ajoutez des participants.", noPeople: "Ajoutez d’abord des participants à ce carnet de voyage.", moved: "Dépense déplacée dans le carnet de voyage.", moveFailed: "Impossible de déplacer la dépense. Vérifiez les détails et les participants.",
  shareFile: "Envoyer le fichier du carnet", shareSummary: "Partager le résumé", receive: "Importer les dépenses des compagnons", shareHelp: "Envoyez le fichier du carnet à vos compagnons. Ils peuvent le choisir dans « Importer les dépenses des compagnons » pour le fusionner avec leur voyage. Les payeurs et les parts exactes sont conservés.", fileSent: "Fichier du carnet partagé.", importTitle: "Fusionner les dépenses du voyage", incoming: "Carnet reçu", target: "Carnet de voyage de destination", newTab: "Enregistrer dans un nouveau carnet", mapping: "Associer les participants", mappingHelp: "Les personnes à gauche proviennent du fichier reçu. Sélectionnez un participant de votre voyage s’il s’agit de la même personne. Sinon, ajoutez une nouvelle personne, même si les noms sont identiques.", newPerson: "Ajouter une nouvelle personne", preview: "Vérifier la fusion", added: "Nouvelles dépenses", duplicates: "Déjà présentes", conflicts: "Versions différentes", conflictHelp: "Ces enregistrements diffèrent : votre version existante est conservée. Vérifiez-les ci-dessous et modifiez les dépenses existantes si nécessaire.", addedTotal: "Montant ajouté", resultTotal: "Dépenses cumulées", merge: "Confirmer et fusionner", importSaved: "Dépenses du voyage enregistrées.", importFailed: "Impossible de fusionner les dépenses. Vérifiez les participants et la capacité du carnet.", invalidPreview: "Vérifiez chaque association. La fusion ne doit pas dépasser les limites de participants, de dépenses ou de devises.", recordCount: "Dépenses", saveNew: "Confirmer et créer le carnet", resultSettlement: "Règlement après fusion", changed: "Le carnet a changé. Vérifiez à nouveau l’aperçu avant de continuer.",
};
export function exchangeText(locale: Locale, key: Key): string { return ({ ko, en, fr })[locale][key]; }
