import { ChevronLeft, ChevronRight, Plus, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { currencyDigits, formatMoney, parseMinorUnits } from "../lib/currency";
import { generalCategoryLabel, t } from "../lib/i18n";
import { addMonths, categoryTotals, monthKey, monthlyTotals, previousMonthComparison, yearlyTotals } from "../lib/statistics";
import { GENERAL_CATEGORIES, type GeneralCategory, type GeneralExpense, type GeneralLedger, type Locale } from "../lib/types";
import { defaultDate } from "../lib/wallet";
import { SheetFrame } from "./Sheets";

type Notify = (message: string, tone?: "success" | "error" | "info") => void;

export function GeneralLedgerView({ ledger, locale, onChange, onNotify }: { ledger: GeneralLedger; locale: Locale; onChange: (ledger: GeneralLedger) => void; onNotify: Notify }) {
  const [selectedMonth, setSelectedMonth] = useState(monthKey(new Date())); const [category, setCategory] = useState<GeneralCategory | "all">("all"); const [formOpen, setFormOpen] = useState(false);
  const year = Number(selectedMonth.slice(0, 4)); const comparison = useMemo(() => previousMonthComparison(ledger.expenses, selectedMonth, category), [ledger.expenses, selectedMonth, category]); const monthCategories = useMemo(() => categoryTotals(ledger.expenses, selectedMonth), [ledger.expenses, selectedMonth]); const bars = useMemo(() => monthlyTotals(ledger.expenses, year, category), [ledger.expenses, year, category]); const years = useMemo(() => yearlyTotals(ledger.expenses, category), [ledger.expenses, category]); const maxBar = Math.max(...bars, 1); const monthExpenses = ledger.expenses.filter((expense) => expense.occurredOn.startsWith(selectedMonth) && (category === "all" || expense.category === category)).sort((a, b) => b.occurredOn.localeCompare(a.occurredOn));
  const update = (expenses: readonly GeneralExpense[]) => onChange(Object.freeze({ ...ledger, expenses: Object.freeze(expenses), updatedAt: new Date().toISOString() }));
  const percentCopy = comparison.percent === null ? t(locale, "newSpending") : comparison.percent === 0 ? t(locale, "noChange") : `${Math.abs(comparison.percent).toLocaleString(locale)}% ${comparison.percent > 0 ? t(locale, "moreSpent") : t(locale, "lessSpent")}`;

  return <section className="ledger-screen general-ledger"><div className="ledger-screen-heading"><div><span>{t(locale, "generalLedger")}</span><h2>{ledger.title}</h2></div><button className="primary-compact" type="button" onClick={() => setFormOpen(true)}><Plus />{t(locale, "addExpense")}</button></div>
    <div className="month-navigation"><button type="button" aria-label={t(locale, "previousMonthButton")} onClick={() => setSelectedMonth(addMonths(selectedMonth, -1))}><ChevronLeft /></button><strong>{new Intl.DateTimeFormat(locale, { year: "numeric", month: "long" }).format(new Date(`${selectedMonth}-01T12:00:00`))}</strong><button type="button" aria-label={t(locale, "nextMonthButton")} onClick={() => setSelectedMonth(addMonths(selectedMonth, 1))}><ChevronRight /></button></div>
    <section className="month-summary"><article><small>{t(locale, "currentMonth")}</small><strong>{formatMoney(comparison.current, ledger.currency, locale)}</strong></article><article className={comparison.difference > 0 ? "increase" : comparison.difference < 0 ? "decrease" : "neutral"}><small>{t(locale, "comparedToPrevious")}</small><strong>{percentCopy}</strong><span>{comparison.difference === 0 ? formatMoney(0, ledger.currency, locale) : `${comparison.difference > 0 ? "+" : "−"}${formatMoney(Math.abs(comparison.difference), ledger.currency, locale)}`}</span></article></section>
    <section className="mobile-panel category-breakdown"><div className="section-heading"><h3>{t(locale, "categorySpending")}</h3><select value={category} onChange={(event) => setCategory(event.target.value as GeneralCategory | "all")}><option value="all">{t(locale, "allCategories")}</option>{GENERAL_CATEGORIES.map((code) => <option value={code} key={code}>{generalCategoryLabel(locale, code)}</option>)}</select></div>{monthCategories.size ? <div className="category-bars">{[...monthCategories].sort(([, a], [, b]) => b - a).map(([code, total]) => <div key={code}><span>{generalCategoryLabel(locale, code)}</span><i><b style={{ width: `${comparison.current ? Math.max(3, total / comparison.current * 100) : 0}%` }} /></i><strong>{formatMoney(total, ledger.currency, locale)}</strong></div>)}</div> : <p className="ledger-empty">{t(locale, "noExpenses")}</p>}</section>
    <section className="mobile-panel annual-chart"><div className="section-heading"><h3>{t(locale, "yearlySpending")}</h3><strong>{year}</strong></div><div className="bar-chart" role="img" aria-label={t(locale, "monthlySpending")}>{bars.map((total, index) => <div key={index}><span className="bar-value">{total ? compactMoney(total, ledger.currency, locale) : ""}</span><i style={{ height: `${Math.max(total ? 7 : 1, total / maxBar * 100)}%` }} /><small>{new Intl.DateTimeFormat(locale, { month: "short" }).format(new Date(year, index, 1))}</small></div>)}</div><div className="annual-footer"><span>{t(locale, "annualTotal")}<strong>{formatMoney(bars.reduce((sum, total) => sum + total, 0), ledger.currency, locale)}</strong></span><span>{t(locale, "monthlyAverage")}<strong>{formatMoney(Math.round(bars.reduce((sum, total) => sum + total, 0) / 12), ledger.currency, locale)}</strong></span></div>{years.length > 1 ? <div className="year-comparison">{years.map((item) => <span key={item.year}>{item.year}<strong>{formatMoney(item.total, ledger.currency, locale)}</strong></span>)}</div> : null}</section>
    <section className="mobile-panel expense-history"><div className="section-heading"><h3>{t(locale, "history")}</h3></div>{monthExpenses.length ? <div className="expense-list">{monthExpenses.map((expense) => <article key={expense.id}><span className={`category-color category-${expense.category}`} /><div><strong>{expense.description}</strong><small>{generalCategoryLabel(locale, expense.category)} · {expense.occurredOn}</small></div><b>{formatMoney(expense.minorUnits, expense.currency, locale)}</b><button type="button" aria-label={t(locale, "delete")} onClick={() => { update(ledger.expenses.filter((candidate) => candidate.id !== expense.id)); onNotify(t(locale, "expenseDeleted"), "success"); }}><Trash2 /></button></article>)}</div> : <p className="ledger-empty">{t(locale, "noExpenses")}</p>}</section>
    <button className="floating-add" type="button" onClick={() => setFormOpen(true)}><Plus />{t(locale, "addExpense")}</button>{formOpen ? <GeneralExpenseSheet ledger={ledger} locale={locale} onClose={() => setFormOpen(false)} onAdd={(expense) => { update([...ledger.expenses, expense]); setFormOpen(false); onNotify(t(locale, "expenseAdded"), "success"); }} onNotify={onNotify} /> : null}</section>;
}

function GeneralExpenseSheet({ ledger, locale, onClose, onAdd, onNotify }: { ledger: GeneralLedger; locale: Locale; onClose: () => void; onAdd: (expense: GeneralExpense) => void; onNotify: Notify }) {
  const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [category, setCategory] = useState<GeneralCategory>("food"); const [occurredOn, setOccurredOn] = useState(defaultDate());
  const submit = () => { const minorUnits = parseMinorUnits(amount, ledger.currency); if (!description.trim()) return onNotify(t(locale, "requiredFields"), "error"); if (!minorUnits) return onNotify(t(locale, "amountInvalid"), "error"); onAdd(Object.freeze({ id: crypto.randomUUID(), description: description.trim(), category, currency: ledger.currency, minorUnits, occurredOn })); };
  return <SheetFrame title={t(locale, "addExpense")} locale={locale} onClose={onClose}><div className="expense-form-grid"><label>{t(locale, "description")}<input value={description} maxLength={500} onChange={(event) => setDescription(event.target.value)} autoFocus /></label><label>{t(locale, "amount")}<div className="amount-field"><input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /><span>{ledger.currency}</span></div></label><label>{t(locale, "category")}<select value={category} onChange={(event) => setCategory(event.target.value as GeneralCategory)}>{GENERAL_CATEGORIES.map((code) => <option value={code} key={code}>{generalCategoryLabel(locale, code)}</option>)}</select></label><label>{t(locale, "date")}<input type="date" value={occurredOn} onChange={(event) => setOccurredOn(event.target.value)} /></label><button className="primary-button wide" type="button" onClick={submit}>{t(locale, "addExpense")}</button></div></SheetFrame>;
}

function compactMoney(minorUnits: number, currency: string, locale: Locale): string { return new Intl.NumberFormat(locale, { notation: "compact", maximumFractionDigits: 1 }).format(minorUnits / 10 ** currencyDigits(currency)); }
