param(
  [Parameter(Mandatory = $true)][string]$BuildDirectory,
  [string]$JavaHome = "$env:LOCALAPPDATA\TogetherToolchain\jdk21\jdk-21.0.12.1+1",
  [string]$AndroidSdk = "$env:LOCALAPPDATA\TogetherToolchain\android-sdk",
  [string]$Bundletool = "$env:LOCALAPPDATA\TogetherToolchain\bundletool-all-1.18.3.jar"
)
$ErrorActionPreference = 'Stop'
$buildRoot = (Resolve-Path -LiteralPath $BuildDirectory).Path
$repoRoot = Split-Path -Parent $PSScriptRoot
$version = (Get-Content -LiteralPath "$repoRoot\package.json" -Raw | ConvertFrom-Json).version
$versionCode = [regex]::Match((Get-Content -LiteralPath "$repoRoot\android\app\build.gradle" -Raw), 'versionCode\s+(\d+)').Groups[1].Value
$env:JAVA_HOME = $JavaHome
$env:Path = "$env:JAVA_HOME\bin;$env:Path"
$buildTools = "$AndroidSdk\build-tools\36.1.0"
$apkPath = "$buildRoot\android\app\build\outputs\apk\release\app-release.apk"
$aabPath = "$buildRoot\android\app\build\outputs\bundle\release\app-release.aab"
if (-not (Select-String -LiteralPath "$buildRoot\build.log" -SimpleMatch "WALLET_BUILD_SUCCEEDED $version" -Quiet)) { throw 'Final release build has not completed' }
foreach ($relativeRoot in @('src', 'public', 'tests', 'docs', 'android\app\src')) {
  $sourceRoot = (Get-Item -LiteralPath "$repoRoot\$relativeRoot").FullName
  foreach ($file in (Get-ChildItem -LiteralPath $sourceRoot -File -Recurse)) {
    $relative = $file.FullName.Substring($sourceRoot.Length + 1)
    # Capacitor regenerates these from dist during this release build; verify
    # those generated bytes against the APK below, not the old local sync.
    if ($relativeRoot -eq 'android\app\src' -and $relative.StartsWith('main\assets\')) { continue }
    $copied = "$buildRoot\$relativeRoot\$relative"
    if ((Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash -ne (Get-FileHash -LiteralPath $copied -Algorithm SHA256).Hash) { throw "Release source differs: $relativeRoot\$relative" }
  }
}
foreach ($relative in @('package.json', 'package-lock.json', 'vite.config.ts', 'tsconfig.json', 'index.html', 'capacitor.config.ts', 'android\app\build.gradle')) {
  if ((Get-FileHash -LiteralPath "$repoRoot\$relative" -Algorithm SHA256).Hash -ne (Get-FileHash -LiteralPath "$buildRoot\$relative" -Algorithm SHA256).Hash) { throw "Release source differs: $relative" }
}
'Release source matches the current workspace'
$testCount = 0
Get-ChildItem -LiteralPath "$buildRoot\android\app\build\test-results\testReleaseUnitTest" -Filter '*.xml' | ForEach-Object {
  [xml]$result = Get-Content -Raw -LiteralPath $_.FullName
  if ([int]$result.testsuite.failures -gt 0 -or [int]$result.testsuite.errors -gt 0) { throw 'Native tests have failures' }
  $testCount += [int]$result.testsuite.tests
}
if ($testCount -lt 35) { throw 'Native tests are missing' }
"Native unit tests passed: $testCount"
$signature = & "$buildTools\apksigner.bat" verify --verbose --print-certs $apkPath
if ($LASTEXITCODE -ne 0) { throw 'APK signature verification failed' }
if (($signature -join "`n") -notmatch '41361b49e87e19971b8aad7c21ab56d0ddee178b26b94e1db056319ef1a31601') { throw 'APK update certificate changed' }
$signature | Where-Object { $_ -match 'Verifies|Verified using|SHA-256' }
$badging = & "$buildTools\aapt.exe" dump badging $apkPath
if ($LASTEXITCODE -ne 0 -or ($badging -join "`n") -notmatch "name='com.seunghyeonkim.walletdiary' versionCode='$versionCode' versionName='$([regex]::Escape($version))'") { throw 'APK version/package mismatch' }
$badging | Where-Object { $_ -match '^package:|^sdkVersion:|^targetSdkVersion:|^native-code:' }
& "$buildTools\zipalign.exe" -c -P 16 4 $apkPath
if ($LASTEXITCODE -ne 0) { throw 'APK alignment verification failed' }
Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive = [System.IO.Compression.ZipFile]::OpenRead($apkPath)
try {
  $webRoot = (Get-Item -LiteralPath "$buildRoot\dist").FullName
  $webFiles = Get-ChildItem -LiteralPath $webRoot -File -Recurse
  foreach ($file in $webFiles) {
    $relative = $file.FullName.Substring($webRoot.Length + 1).Replace('\', '/')
    $entry = $archive.GetEntry("assets/public/$relative")
    if (-not $entry) { throw "APK missing web asset: $relative" }
    $stream = $entry.Open()
    $hasher = [System.Security.Cryptography.SHA256]::Create()
    try { $apkHash = [Convert]::ToHexString($hasher.ComputeHash($stream)) } finally { $stream.Dispose(); $hasher.Dispose() }
    if ($apkHash -ne (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash) { throw "APK stale web asset: $relative" }
  }
  "APK web assets match final build: $($webFiles.Count) files"
  $pdfResources = @($webFiles | Where-Object { $_.FullName.StartsWith("$webRoot\pdf-resources\") })
  if ($pdfResources.Count -ne 198) { throw 'Offline PDF decoder assets missing' }
  'Offline PDF resource assets verified: 198'
  $nativeCount = 0
  foreach ($entry in $archive.Entries) {
    if ($entry.FullName -notmatch '^lib/(arm64-v8a|x86_64)/.*\.so$') { continue }
    $stream = $entry.Open()
    $memory = [System.IO.MemoryStream]::new()
    try { $stream.CopyTo($memory); $bytes = $memory.ToArray() } finally { $stream.Dispose(); $memory.Dispose() }
    if ($bytes[0] -ne 127 -or $bytes[1] -ne 69 -or $bytes[4] -ne 2 -or $bytes[5] -ne 1) { throw "Unexpected ELF: $($entry.FullName)" }
    $phOffset = [BitConverter]::ToUInt64($bytes, 32)
    $phSize = [BitConverter]::ToUInt16($bytes, 54)
    $phCount = [BitConverter]::ToUInt16($bytes, 56)
    for ($i = 0; $i -lt $phCount; $i++) {
      $offset = [int]($phOffset + $i * $phSize)
      if ([BitConverter]::ToUInt32($bytes, $offset) -ne 1) { continue }
      $alignment = [BitConverter]::ToUInt64($bytes, $offset + 48)
      if ($alignment -lt 16384) { throw "Native library is not 16KB aligned: $($entry.FullName)" }
    }
    $nativeCount++
  }
  if ($nativeCount -lt 2) { throw '64-bit native libraries missing' }
  "64-bit ELF 16KB load alignment verified: $nativeCount libraries"
} finally { $archive.Dispose() }
$jarResult = & "$env:JAVA_HOME\bin\jarsigner.exe" -verify $aabPath
if ($LASTEXITCODE -ne 0 -or ($jarResult -join "`n") -notmatch 'jar verified') { throw 'AAB signature verification failed' }
'AAB JAR signature verified'
$bundleValidation = & "$env:JAVA_HOME\bin\java.exe" -jar $Bundletool validate "--bundle=$aabPath"
if ($LASTEXITCODE -ne 0) { throw 'AAB structure validation failed' }
'AAB bundle structure verified'
Copy-Item -LiteralPath $apkPath -Destination "$repoRoot\release\Wallet-Diary-v$version.apk" -Force
Copy-Item -LiteralPath $aabPath -Destination "$repoRoot\release\Wallet-Diary-v$version.aab" -Force
Get-FileHash -LiteralPath "$repoRoot\release\Wallet-Diary-v$version.apk", "$repoRoot\release\Wallet-Diary-v$version.aab" -Algorithm SHA256 | Select-Object Path,Hash | ConvertTo-Json -Compress
'WALLET_RELEASE_VERIFIED'
